baseurl = "http://www.tsdye.online/harris-matrix/"
languageCode = "en-us"
title = "HM"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Thomas S. Dye"
	description = "Sequence diagrams for archaeology"
	copyright = "Released under the GNU General Public License v3.0"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/tsdye/harris-matrix"

	version = "0.3.0"
	logo = "logo/hm-logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "amber"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "tsdye"
	email   = "tsd@tsdye.com"

[[menu.main]]
  name = "Home"
  url = "homepage/"
  weight = 1

[[menu.main]]
	name   = "The hm package"
	url    = "hm-package/"
	weight = 20

[[menu.main]]
	name   = "Requirements"
	url    = "requirements/"
	weight = 40

[[menu.main]]
	name   = "Example projects"
	url    = "example-projects/"
	weight = 60

[[menu.main]]
	name   = "Classifiers"
	url    = "classifiers/"
	weight = 80

[[menu.main]]
	name   = "Graph attributes"
	url    = "graph-attributes/"
	weight = 100

[[menu.main]]
	name   = "Configuration file"
	url    = "configuration-file/"
	weight = 120

[[menu.main]]
	name   = "Data tables"
	url    = "data-tables/"
	weight = 140

[[menu.main]]
	name   = "Technical description"
	url    = "technical-description/"
	weight = 160

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
