#+OPTIONS: broken-links:t todo:nil
#+AUTHOR: Hawaii J20
#+hugo_base_dir: /home/dk/Public/projects/958-web-site/public-node/j20-immigration/
#+hugo_auto_set_lastmod: t
* Homepage
  :PROPERTIES:
  :EXPORT_HUGO_SECTION:
  :EXPORT_AUTHOR: "Hawaii J20"
  :END:

* FAQ
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: post
  :END:

** DONE Why should undocumented immigrants be allowed to stay?
   CLOSED: [2018-06-12 Tue 12:32]
   :PROPERTIES:
   :EXPORT_FILE_NAME: allow-to-stay
   :EXPORT_HUGO_MENU: "main"
   :END:

*** Question
Many immigrants have followed the law and are in our country legally.
Why should aliens who entered our country illegally be allowed to live here?


*** Answer
Most of the undocumented immigrants who live in Hawaii have done nothing
illegal arising from their immigration status. Immigrants are undocumented for
one of two reasons: (1) They have entered our country by crossing the border
without being processed, which is a misdemeanor, or (2) They have entered our
country with a visa, but have overstayed, which is a civil offense, and not a
crime. The great majority of undocumented immigrants in Hawaii have overstayed
their visas.


** DONE Don't undocumented immigrants pose a criminal threat?
   CLOSED: [2018-06-12 Tue 14:31]
   :PROPERTIES:
   :EXPORT_FILE_NAME: criminal-threat
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
Attorney General Jeff Sessions has characterized the Chicago sanctuary law as
"an official policy of protecting criminal aliens who prey on their own
residents." Along the same lines, President Trump claimed that "sanctuary cities release
thousands of criminal aliens out of our prisons and jails and back into our
communities. They go into those sanctuary cities when they see them. They go
there because they feel they're safe, and in many cases, they are very bad
actors. We have gang members; we have predators, rapists, killers, a lot of bad
people."  Don't undocumented aliens pose a criminal threat?

*** Answer
Some undocumented immigrants do pose a criminal threat, but most do not. With
respect to crime in general, undocumented immigrants have a crime rate that is
44% below that of native-born U.S. citizens. The average undocumented immigrant
poses less of a criminal threat than the average U.S. citizen.


** DONE What is wrong with deporting undocumented aliens?
   CLOSED: [2018-06-12 Tue 12:32]
   :PROPERTIES:
   :EXPORT_FILE_NAME: wrong-with-deporting
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
Why shouldn’t undocumented immigrants be deported?

*** Answer
The estimated 45,000 undocumented immigrants living in Hawaii are so well
integrated into our communities that even their friends and neighbors may not
know they are undocumented. Undocumented immigrants work, pay taxes, and send
their children to school. Some are leaders in our communities. Many are married
to U.S. citizens, and many of their children are U.S. citizens by birth.
Deporting undocumented immigrants would break up families and remove the main
source of financial support for many minor children.

** Why shouldn't Hawai`i comply with federal law?
   :PROPERTIES:
   :EXPORT_FILE_NAME: comply-with-feds
   :EXPORT_DATE: 2018-06-12
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
The federal government is following the law in trying to remove
illegal aliens. Why should the State refuse to comply with federal law?

*** Answer
Hawai`i is following the law and it will continue to follow the law if it enacts
a sanctuary law. Immigration and the enforcement of immigration law is purely a
federal function. The State and its counties receive no federal funds to support
federal immigration programs. Yet President Trump wants states and their local
governments to help federal immigration agencies, such as the federal
Immigration and Customs Enforcement agency (ICE). For example, Trump wants local
police to act as ICE agents to help identify and deport all undocumented
immigrants.

** Hasn't the US always deported undocumented immigrants?
   :PROPERTIES:
   :EXPORT_FILE_NAME: always-deported
   :EXPORT_DATE: 2018-06-12
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
Undocumented immigrants are deportable. Hasn't the US always deported
undocumented immigrants?

*** Answer
In the past, the Obama administration was responsible for deporting
millions of undocumented immigrants who had committed serious crimes. However,
those who had committed no serious crime were allowed to remain in the U.S.
Today, Trump seeks to deport all undocumented immigrants without exception,
whether they have committed a serious crime or not. The federal
Immigration and Customs Enforcement agency (ICE) has recently used
increasingly harsh tactics to identify and deport undocumented immigrants,
including separating children from their parents. Local police should not get
involved with that kind of questionable activity because there is more than
enough serious crime in our communities for police to handle.

** Why should the state provide a safe space for undocumented immigrants?
   :PROPERTIES:
   :EXPORT_FILE_NAME: safe-space
   :EXPORT_DATE: 2018-06-12
   :EXPORT_AUTHOR: "Hawaii J20"
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
The sanctuary state bill the State Legislature considered in the
2018 session would have provided a safe place for illegal aliens. Why should the
State do that?

*** Answer
The sanctuary bill considered in 2018 does not provide any additional
protections to undocumented immigrants than it does to citizens. There is no law
requiring the State or its counties to assist federal Immigration and Customs
Enforcement agency (ICE), and the sanctuary state bill merely limits Hawaii’s
local law enforcement agencies from assisting ICE. Some state and local
governments across the nation do provide assistance to ICE, while more than 600
others refuse to do so because they believe assisting ICE will disrupt their
communities.

** Why shouldn't the state assist ICE?
   :PROPERTIES:
   :EXPORT_FILE_NAME: assist-ice
   :EXPORT_DATE: 2018-06-12
   :EXPORT_AUTHOR: "Hawaii J20"
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
Why shouldn't local law enforcement agencies assist their law enforcement
colleagues at the federal Immigration and Customs Enforcement agency (ICE)?

*** Answer
Immigration enforcement is a federal function. When undocumented
immigrants fear that local police are acting as ICE agents who can initiate
deportation, they are reluctant to make contact with the police. They are
reluctant to report crimes and suspected crimes to the police, and they are
reluctant to come forth as witnesses to crimes. That makes our communities less
safe for everyone.

** Doesn't a state sanctuary law contradict federal law?
   :PROPERTIES:
   :EXPORT_FILE_NAME: contradict-fed-law
   :EXPORT_DATE: 2018-06-12
   :EXPORT_AUTHOR: "Hawaii J20"
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
Doesn't a state sanctuary law contradict federal law?

*** Answer
Hawaii’s proposed sanctuary state bill does not conflict with federal
law because it allows federal immigration efforts to continue. Constitutional
experts agree that the provisions of Hawaii’s proposed sanctuary state bill are
legal. None of its provisions have been found by any court to be in violation of
federal law or the U.S. Constitution.

** Aren't undocumented immigrants a drain on our social services?
   :PROPERTIES:
   :EXPORT_FILE_NAME: social-services
   :EXPORT_DATE: 2018-06-12
   :EXPORT_AUTHOR: "Hawaii J20"
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
Illegal aliens are a drain on our communities because they get welfare
and free health care, so why shouldn’t they be deported?

*** Answer
Undocumented immigrants support government financially because they pay
taxes. Yet they do not qualify for the most costly government assistance
programs, such as Social Security, Medicare, and Medicaid, although they may
qualify for some smaller government assistance programs. Studies show that
undocumented immigrants pay about as much in taxes as they receive in government
programs.

** Won't a sanctuary law disrupt the flow of federal funds to Hawai`i?
   :PROPERTIES:
   :EXPORT_FILE_NAME: disrupt-fed-funds
   :EXPORT_DATE: 2018-06-12
   :EXPORT_AUTHOR: "Hawaii J20"
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
If Hawaii refuses to cooperate with Trump and his immigration
policies, he will retaliate by withholding federal grants to Hawaii. Why should
Hawai`i unnecessarily put hundreds of millions of federal dollars at risk?

*** Answer
Actually, very little federal funding would be at risk, because federal
law allows grant moneys to be withheld only when a state does not comply with
the requirements of that particular grant. There is only one grant related to
immigration enforcement, and Hawaii receives a relatively small amount from it.
It should be noted that, despite Hawaii’s high-profile challenge to Trump’s
Muslim travel ban, the federal budget proposed by Trump would actually increase
total federal funding for Hawaii.

** Why should we worry about people different than us?
   :PROPERTIES:
   :EXPORT_FILE_NAME: waste-time
   :EXPORT_DATE: 2018-06-12
   :EXPORT_AUTHOR: "Hawaii J20"
   :EXPORT_HUGO_MENU: :menu "main"
   :END:

*** Question
Why should we waste time worrying about undocumented immigrants?

*** Answer
Hawai`i has a rich immigrant heritage that continues and should be allowed
continue, despite any risk of losing a small amount of federal grant money. Most
of us who live in Hawaii are either immigrants or the descendants of immigrants
who sought better lives for themselves and their children. Immigrants have
contributed significantly to our society and the unique character of Hawaii’s
culture. Today’s immigrants, whether documented or not, are no different.
